In [1]:
import numpy as np

X = np.array([
    [0, 0, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 0],
    [0, 0, 1, 1],
    [0, 1, 0, 0],
    [0, 1, 0, 1],
    [0, 1, 1, 0],
    [0, 1, 1, 1],
    [1, 0, 0, 0],
    [1, 0, 0, 1],
    [1, 0, 1, 0],
    [1, 0, 1, 1],
    [1, 1, 0, 0],
    [1, 1, 0, 1],
    [1, 1, 1, 0],
    [1, 1, 1, 1]
])

# Output = 1 if sum of inputs >= 3
y = np.array([
    [0],
    [0],
    [0],
    [0],
    [0],
    [0],
    [0],
    [1],
    [0],
    [0],
    [0],
    [1],
    [0],
    [1],
    [1],
    [1]
])

In [2]:
input_layer = 4
output_layer = 1
hidden1 = 4
hidden2 = 3
epochs = 10000
lr = 0.1
w1 = np.random.randn(input_layer,hidden1)
b1 = np.zeros((1,hidden1))
w2 = np.random.randn(hidden1,hidden2)
b2 = np.zeros((1,hidden2))
w3 = np.random.randn(hidden2,output_layer)
b3 = np.zeros((1,1))
epsilon = 1e-8

gw1 = np.zeros_like(w1)
gb1 = np.zeros_like(b1)

gw2 = np.zeros_like(w2)
gb2 = np.zeros_like(b2)

gw3 = np.zeros_like(w3)
gb3 = np.zeros_like(b3)

In [3]:
for i in range(epochs):
    z1 = np.dot(X, w1) + b1
    a1 = np.maximum(0, z1)
    z2 = np.dot(a1, w2) + b2
    a2 = np.maximum(0, z2)
    z3 = np.dot(a2, w3) + b3
    a3 = 1 / (1 + np.exp(-z3))

    # Loss

    loss = -np.sum(
        y * np.log(a3 + 1e-8) +
        (1-y) * np.log(1-a3 + 1e-8)
    ) / X.shape[0]

    dw3 = np.dot(a2.T, (a3 - y)) / X.shape[0]
    db3 = np.sum(a3 - y) / X.shape[0]

    da2 = np.dot((a3 - y), w3.T)
    dz2 = da2 * (z2 > 0).astype(float)
    dw2 = np.dot(a1.T, dz2) / X.shape[0]
    db2 = np.sum(dz2, axis=0, keepdims=True) / X.shape[0]

    da1 = np.dot(dz2, w2.T)
    dz1 = da1 * (z1 > 0).astype(float)
    dw1 = np.dot(X.T, dz1) / X.shape[0]
    db1 = np.sum(dz1, axis=0, keepdims=True) / X.shape[0]
    
    gw1 += dw1 ** 2
    gb1 += db1 ** 2

    gw2 += dw2 ** 2
    gb2 += db2 ** 2

    gw3 += dw3 ** 2
    gb3 += db3 ** 2
    
    w1 -= (lr * dw1) / (np.sqrt(gw1) + epsilon)
    b1 -= (lr * db1) / (np.sqrt(gb1) + epsilon)

    w2 -= (lr * dw2) / (np.sqrt(gw2) + epsilon)
    b2 -= (lr * db2) / (np.sqrt(gb2) + epsilon)

    w3 -= (lr * dw3) / (np.sqrt(gw3) + epsilon)
    b3 -= (lr * db3) / (np.sqrt(gb3) + epsilon)

In [4]:
print('w1',w1)
print('w2',w2)
print('w3',w3)
print('b1',b1)
print('b2',b2)
print('b3',b3)

w1 [[-0.02835396 -0.62481428  2.41503758  0.83551331]
 [-0.71494094 -0.69024492  1.38087946  0.25055893]
 [-0.06045589  0.2699119   2.77399287 -0.50472019]
 [-0.29910469  0.93170775  3.23315294 -1.36515468]]
w2 [[-0.77932872  0.4962727  -0.07079444]
 [ 2.49308715  2.22488914 -0.81273477]
 [-0.95481032 -0.82867693 -0.69829093]
 [ 1.40732307  1.28206055 -1.51357857]]
w3 [[-4.68885246]
 [-1.1066563 ]
 [-0.21117188]]
b1 [[ 0.          1.04494241 -1.89946976  1.61935551]]
b2 [[1.35841018 1.04701209 0.        ]]
b3 [[5.34930509]]
