In [1]:
import numpy as np

X = np.array([
    [0, 0, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 0],
    [0, 0, 1, 1],
    [0, 1, 0, 0],
    [0, 1, 0, 1],
    [0, 1, 1, 0],
    [0, 1, 1, 1],
    [1, 0, 0, 0],
    [1, 0, 0, 1],
    [1, 0, 1, 0],
    [1, 0, 1, 1],
    [1, 1, 0, 0],
    [1, 1, 0, 1],
    [1, 1, 1, 0],
    [1, 1, 1, 1]
])

# Output = 1 if sum of inputs >= 3
y = np.array([
    [0],
    [0],
    [0],
    [0],
    [0],
    [0],
    [0],
    [1],
    [0],
    [0],
    [0],
    [1],
    [0],
    [1],
    [1],
    [1]
])

In [2]:
input_layer = 4
output_layer = 1
hidden1 = 4
hidden2 = 3
epochs = 10000
lr = 0.1
w1 = np.random.randn(input_layer,hidden1)
b1 = np.zeros((1,hidden1))
w2 = np.random.randn(hidden1,hidden2)
b2 = np.zeros((1,hidden2))
w3 = np.random.randn(hidden2,output_layer)
b3 = np.zeros((1,1))
vw1 = np.zeros_like(w1)
vb1 = np.zeros_like(b1)
vw2 = np.zeros_like(w2)
vb2 = np.zeros_like(b2)
vw3 = np.zeros_like(w3)
vb3 = np.zeros_like(b3)
beta = 0.9

In [5]:
for i in range(epochs):
    w1_look = w1 - beta * vw1
    b1_look = b1 - beta * vb1

    w2_look = w2 - beta * vw2
    b2_look = b2 - beta * vb2

    w3_look = w3 - beta * vw3
    b3_look = b3 - beta * vb3


    z1 = np.dot(X, w1_look) + b1_look
    a1 = np.maximum(0, z1)      

    z2 = np.dot(a1, w2_look) + b2_look
    a2 = np.maximum(0, z2)      

    z3 = np.dot(a2, w3_look) + b3_look
    a3 = 1 / (1 + np.exp(-z3))


    loss = -np.mean(
        y * np.log(a3 + 1e-8)
        + (1 - y) * np.log(1 - a3 + 1e-8)
    )


    dz3 = a3 - y

    dw3 = np.dot(a2.T, dz3) / X.shape[0]
    db3 = np.sum(dz3, axis=0, keepdims=True) / X.shape[0]

    da2 = np.dot(dz3, w3_look.T)
    dz2 = da2 * (z2 > 0).astype(float)

    dw2 = np.dot(a1.T, dz2) / X.shape[0]
    db2 = np.sum(dz2, axis=0, keepdims=True) / X.shape[0]

    da1 = np.dot(dz2, w2_look.T)
    dz1 = da1 * (z1 > 0).astype(float)

    dw1 = np.dot(X.T, dz1) / X.shape[0]
    db1 = np.sum(dz1, axis=0, keepdims=True) / X.shape[0]

    vw1 = beta * vw1 + lr * dw1
    vb1 = beta * vb1 + lr * db1

    vw2 = beta * vw2 + lr * dw2
    vb2 = beta * vb2 + lr * db2

    vw3 = beta * vw3 + lr * dw3
    vb3 = beta * vb3 + lr * db3

    w1 -= vw1
    b1 -= vb1

    w2 -= vw2
    b2 -= vb2

    w3 -= vw3
    b3 -= vb3

In [6]:
print('w1',w1)
print('w2',w2)
print('w3',w3)
print('b1',b1)
print('b2',b2)
print('b3',b3)

w1 [[ 0.14878379 -0.91799199 -1.36403913  0.28119542]
 [ 0.08752428 -0.67777476 -1.53010072  0.31729185]
 [-1.26028804 -0.296098   -1.57607607 -1.94931566]
 [-1.25796308  1.18672784  1.89325109 -2.01726517]]
w2 [[ 1.5874448  -0.17386984 -1.07466975]
 [ 0.35912957 -0.89492495  0.75291339]
 [-0.55096142 -1.07496035  3.02814774]
 [ 2.75272447 -1.14797195  0.03858037]]
w3 [[-2.27433357]
 [-1.31108092]
 [-3.09012402]]
b1 [[0.89017873 0.11197122 0.97206508 1.24612453]]
b2 [[-0.17064159  0.         -0.28611756]]
b3 [[0.51081704]]
