# Principal Component Analysis (PCA)

Principal Component Analysis (PCA) is a dimensionality reduction technique used to transform a dataset into a smaller set of uncorrelated variables called principal components.

### Objectives

1. Reduce the number of features.
2. Preserve as much information (variance) as possible.
3. Remove redundancy caused by correlated features.

### PCA Workflow

1. Standardize the data.
2. Compute the covariance matrix.
3. Calculate eigenvalues and eigenvectors.
4. Sort eigenvalues in descending order.
5. Select the top principal components.
6. Project the data onto the new feature space.

In [1]:
import numpy as np
import pandas as pd

np.random.seed(42)

n_samples = 300

x1 = np.random.normal(0, 1, n_samples)

# Correlated features
x2 = 2 * x1 + np.random.normal(0, 0.5, n_samples)
x3 = x1 - x2 + np.random.normal(0, 0.2, n_samples)

X = np.column_stack([x1, x2, x3])

df = pd.DataFrame(
    X,
    columns=["feature1", "feature2", "feature3"]
)

print(df.head())
print("Shape:", X.shape)

   feature1  feature2  feature3
0  0.496714  0.578931  0.069181
1 -0.138264 -0.556619  0.233922
2  0.647689  1.669024 -0.847414
3  1.523030  3.351245 -1.557087
4 -0.234153 -0.478758  0.327291
Shape: (300, 3)


In [2]:
X.mean(axis=0)

array([-0.00554856, -0.02184211,  0.03273237])

In [3]:
X_mean = X - X.mean(axis=0)

In [4]:
X_cov = np.dot(X_mean.T,X_mean)/(X.shape[0]-1)

In [5]:
X_cov

array([[ 0.96863722,  1.91810721, -0.95689018],
       [ 1.91810721,  4.02905718, -2.12879067],
       [-0.95689018, -2.12879067,  1.22205556]])

In [6]:
eigenvalues, eigenvectors = np.linalg.eig(X_cov)

In [7]:
idx = np.argsort(eigenvalues)[::-1]

In [8]:
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]

In [9]:
X_pca = np.dot(X_mean,eigenvectors[:,:2])

In [10]:
X_pca[:5]

array([[-0.66753832,  0.41025929],
       [ 0.57380462,  0.0131809 ],
       [-2.01041938, -0.08020008],
       [-4.02587274,  0.11014703],
       [ 0.58800297,  0.03203439]])

## Principal Component Analysis using Scikit-Learn

To validate the from-scratch implementation, we use Scikit-Learn's PCA module.

The algorithm:

1. Computes the covariance structure of the data.
2. Finds the principal components using eigen decomposition.
3. Sorts components according to explained variance.
4. Projects the data onto the selected principal components.

The transformed data, explained variance, and principal components are compared with the results obtained from the manual implementation.

In [11]:
from sklearn.decomposition import PCA

# Reduce from 3 dimensions to 2 dimensions
pca = PCA(n_components=2)

X_pca_sklearn = pca.fit_transform(X_mean)

print("Original Shape:", X.shape)
print("Reduced Shape:", X_pca_sklearn.shape)

print("\nTransformed Data:")
print(X_pca_sklearn[:5])

Original Shape: (300, 3)
Reduced Shape: (300, 2)

Transformed Data:
[[ 0.66753832  0.41025929]
 [-0.57380462  0.0131809 ]
 [ 2.01041938 -0.08020008]
 [ 4.02587274  0.11014703]
 [-0.58800297  0.03203439]]
