In [1]:
import numpy as np

X = np.array([
    [0, 0, 0, 0],
    [0, 0, 0, 1],
    [0, 0, 1, 0],
    [0, 0, 1, 1],
    [0, 1, 0, 0],
    [0, 1, 0, 1],
    [0, 1, 1, 0],
    [0, 1, 1, 1],
    [1, 0, 0, 0],
    [1, 0, 0, 1],
    [1, 0, 1, 0],
    [1, 0, 1, 1],
    [1, 1, 0, 0],
    [1, 1, 0, 1],
    [1, 1, 1, 0],
    [1, 1, 1, 1]
])

# Output = 1 if sum of inputs >= 3
y = np.array([
    [0],
    [0],
    [0],
    [0],
    [0],
    [0],
    [0],
    [1],
    [0],
    [0],
    [0],
    [1],
    [0],
    [1],
    [1],
    [1]
])

In [2]:
input_layer = 4
output_layer = 1
hidden1 = 4
hidden2 = 3
epochs = 10000
lr = 0.1
w1 = np.random.randn(input_layer,hidden1)
b1 = np.zeros((1,hidden1))
w2 = np.random.randn(hidden1,hidden2)
b2 = np.zeros((1,hidden2))
w3 = np.random.randn(hidden2,output_layer)
b3 = np.zeros((1,1))
vw1 = np.zeros_like(w1)
vb1 = np.zeros_like(b1)
vw2 = np.zeros_like(w2)
vb2 = np.zeros_like(b2)
vw3 = np.zeros_like(w3)
vb3 = np.zeros_like(b3)
beta = 0.95
epsilon = 1e-8

In [3]:
for i in range(epochs):
    z1 = np.dot(X, w1) + b1
    a1 = np.maximum(0, z1)
    z2 = np.dot(a1, w2) + b2
    a2 = np.maximum(0, z2)
    z3 = np.dot(a2, w3) + b3
    a3 = 1 / (1 + np.exp(-z3))

    # Loss

    loss = -np.sum(
        y * np.log(a3 + 1e-8) +
        (1-y) * np.log(1-a3 + 1e-8)
    ) / X.shape[0]

    dw3 = np.dot(a2.T, (a3 - y)) / X.shape[0]
    db3 = np.sum(a3 - y) / X.shape[0]

    da2 = np.dot((a3 - y), w3.T)
    dz2 = da2 * (z2 > 0).astype(float)
    dw2 = np.dot(a1.T, dz2) / X.shape[0]
    db2 = np.sum(dz2, axis=0, keepdims=True) / X.shape[0]

    da1 = np.dot(dz2, w2.T)
    dz1 = da1 * (z1 > 0).astype(float)
    dw1 = np.dot(X.T, dz1) / X.shape[0]
    db1 = np.sum(dz1, axis=0, keepdims=True) / X.shape[0]
    
    vw1 = beta*vw1 + (1-beta)*(dw1)**2
    vb1 = beta*vb1 + (1-beta)*(db1)**2
    vw2 = beta*vw2 + (1-beta)*(dw2)**2
    vb2 = beta*vb2 + (1-beta)*(db2)**2
    vw3 = beta*vw3 + (1-beta)*(dw3)**2
    vb3 = beta*vb3 + (1-beta)*(db3)**2
    
    w1 -= (lr * dw1) / (np.sqrt(vw1) + epsilon)
    b1 -= (lr * db1) / (np.sqrt(vb1) + epsilon)

    w2 -= (lr * dw2) / (np.sqrt(vw2) + epsilon)
    b2 -= (lr * db2) / (np.sqrt(vb2) + epsilon)

    w3 -= (lr * dw3) / (np.sqrt(vw3) + epsilon)
    b3 -= (lr * db3) / (np.sqrt(vb3) + epsilon)

In [4]:
print('w1',w1)
print('w2',w2)
print('w3',w3)
print('b1',b1)
print('b2',b2)
print('b3',b3)

w1 [[ 1.41584102  0.11834884  1.17240974 -0.16660198]
 [ 1.4066721  -1.09744684 -1.29148461 -0.59421781]
 [ 1.39749563  0.76078576 -2.86462281  1.16417359]
 [ 1.40666966 -0.80388374 -0.80936852 -1.95717575]]
w2 [[-3.09181129  3.48312851  0.25262437]
 [-0.09455747  0.55881727  0.36680147]
 [ 2.96455861  1.25289223  1.02268552]
 [-0.00742015 -2.02349759 -1.85985258]]
w3 [[-6.07011037]
 [ 6.34219839]
 [ 1.29231964]]
b1 [[-2.80420412 -0.99968162  0.9284442  -1.19597818]]
b2 [[ 5.00761057 -0.0319179  -1.73402492]]
b3 [[2.07427685]]
